### ISSUE TITLE
Forget Docker, JAMstack is the future

### ISSUE THREAD

**Issue by TheCodeKing** [contentful/contribution-program#30]
I've literally just written an article all about JAMstack, and which also mentions Contentful.

It's about increasing agility in businesses without going down the rabbit-hole of investing time and effort in infrastructure technology such as Docker. This is a side effect of companies investing in traditional CMS products and coupling themselves to specific stacks. They get caught up in infrastructure problems and complexity that shouldn't exist. They think the answer is Docker and getting better at dealing with infrastructure when really all they need is SaaS solutions (and JAMstack).

Moving to SaaS like Contentful and using JAMstack allows companies to refocus on the right part of the value chain and leverage Cloud services as commodities. It allows them to go faster and gain a competitive edge.

Not sure if you accept an article that's already written, but would like to submit this:

https://hackernoon.com/forget-docker-the-future-is-jamstack-aae5bcaf4616

**Comment by Shy** [comment]
Hey @TheCodeKing,

Thanks for sharing this with us. We do pay for reposts through our contribution program, but I'm not sure our blog is the best place for this post. It's a little too general for us. With the contribution program, we're looking for articles with a strong Contentful focus rather than just a mention.
