### ISSUE TITLE
Article published: Building a Contentful + Next.Js Blog

### ISSUE THREAD

**Issue by abedzantout** [contentful/contribution-program#37]
Hello everyone,

I apologize for not writing here sooner, as I have just discovered this thread.

The article I've written is about combining Contentful and Next.Js to create a static blog.

Here are the main bullets:

- I have already written the article and published it today [here](https://www.techhive.io/our-insights/how-to-build-a-powerful-blog-with-nextjs-and-contentful), and on [medium](https://medium.com/techhive-io/how-to-build-a-powerful-blog-with-nextjs-and-contentful-e4919ec78420).
- I have created a [starter template](https://github.com/techhiveIO/nextjs-static-starter-kit) to help people get started,
- This article tackles different aspects of creating a blog, including dynamic meta tags and SEO compatibility (i.e: Google Analytics tracking),
- The blog is exported into a static blog,
- Multiple Gists are written to help guide the reader throughout the entire tutorial,
- I also included an automatic script that utilizes contentful-migration and contentful-cli to create data entries

Hope you guys like it! We're using Contentful to power our Techhive.IO's new blog!

**Comment by Shy** [comment]
Hey Abed,

I'm struggling a little with the link you shared. When I go to the root techhive.io website and click your insights tab and then the article it renders. But when I got directly to the link it doesn't work for me. 

I like the article, but I want to share it with the Contentful team before moving forward. Anything I'm doing wrong? 
![techhive io](https://user-images.githubusercontent.com/1316340/65537818-f74d1300-ded3-11e9-857b-154762d46ec0.gif)

**Comment by abedzantout** [comment]
Hi @Shy,

That's very weird. 

In any case, please find the medium link [here](https://medium.com/techhive-io/how-to-build-a-powerful-blog-with-nextjs-and-contentful-e4919ec78420).

I'll update the original post also

**Comment by Shy** [comment]
Perfect. I'll pass it on and let you know what everyone thinks. :)

**Comment by Shy** [comment]
Hey @abedzantout, I think we're going to pass on reposting this article. We've had a few articles about next JS and contentful already. My brief search actually found 5 next JS articles on our blog already. Since it's a repost rather than content that would get posted to our site first, it doesn't make sense for us to move forward with it.

That said we do really like this article, and if you're working on something contentful related we'd want to hear about it. Would be awesome if we'd be able to go through the contribution program for anything else you might have in your pipeline.
