### ISSUE TITLE
Author Wanted: How to work with Designers

### ISSUE THREAD

**Issue by Shy** [contentful/contribution-program#48]

**Comment by allanwhite** [comment]
I'm a designer with 25 years of experience and have worked extensively with developers. This sounds like a great topic. @Shy Can you tell me more about what you're looking for?

**Comment by Shy** [comment]
Hey @allanwhite, we're pretty open on where this article could go. Off the top of my head it could be interesting to talk about and of the following: 

How you can include design information inside Contentful (color schemes). 
Component Design and Content architecture 
I'd still wanting to read something about your Figma and Contentful integrations

I'm a developer so design workflow isn't something I'm an expert on so happy to hear your ideas too!

**Comment by allanwhite** [comment]
This is a different topic @Shy, but I may propose an envisioned Contentful (data) > Figma (design) > Contentful (image assets) round-trip workflow. It doesn't exist yet, but I think it could. And would rock!

**Comment by Shy** [comment]
Sorry on my slow response time here. I was at JAMStackConf all last week and spent the weekend recovering. 

I think doing anything about Contentful and Figma would be awesome. I saw your posts about it in the community slack and was hoping you'd be wanting to write about it. Any chance you'd be able to spin up an [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) so we can give you feedback on the post before you start doing the hard work on it?

**Comment by allanwhite** [comment]
@Shy I'm going to have to come back to this (job hunting! =) I would be up for a video chat to talk through possibilities (your dev experience would be useful). The video itself might be worth putting in a post. Basically UX product discovery. Probably need a storyboard to summarize the output of that.

Ideas to chew on (CF + Figma automated design workflow):

* I wonder if a figma plugin could talk to Contentful via the API and *request new fields*?
* Could there be some sort of field discovery feature in a Figma plugin? "What fields to I have and what are their fieldnames?" Stuff like this is of course dependent on workflow rules. 
* I wonder how a GraphiQL explorer could be useful for shaping the output. Maybe it's the "middleware" between the two.
* I haven't dug into the plugin API of Figma "because designer", but I would want to know if it can create new artboards based on the number of records. The approach I tried requires making them manually.

Would love to hear any other ideas or use cases.

**Comment by Shy** [comment]
Sorry on my slow response to this. A video chat would be great. What's your schedule like for Thursday or Friday? I'm open both days anytime after 1pm EST.

**Comment by realityking** [comment]
Since @allanwhite now works at Contentful 🎉, this article is again free for the taking. Anyone interested?
